version: '2'
services:
    mycompany-app:
        image: mycompany
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mycompany-mysql:3306/mycompany?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    mycompany-mysql:
        extends:
            file: mysql.yml
            service: mycompany-mysql
